-- Initial schema bootstrap for Compliance IQ production deployments.
-- Apply using your managed DB migration pipeline.

-- Tables are generated by SQLAlchemy metadata in app startup as fallback,
-- but production should use controlled migrations.
