from datetime import datetime

SEED_REGULATIONS = [
    {
        "code": "OSHA-29CFR-1910.1200",
        "title": "Hazard Communication",
        "authority": "OSHA",
        "applies_to_sector": "all",
        "criteria": {"stores_hazardous_chemicals": True, "requires_sds_program": True},
        "required_actions": [
            "Maintain written hazard communication program",
            "Maintain and update Safety Data Sheets (SDS)",
            "Train employees on chemical hazards and labels",
        ],
        "source_name": "OSHA 29 CFR 1910.1200",
        "source_url": "https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.1200",
        "version": "2024",
        "status": "approved",
        "last_verified_on": datetime(2026, 4, 17),
        "expert_reviewer": "Dana Cole, CSP",
        "expert_credentials": "Certified Safety Professional",
        "expert_review_notes": "Rule text and applicability reviewed against OSHA standard page.",
    },
    {
        "code": "OSHA-29CFR-1910.147",
        "title": "Control of Hazardous Energy (Lockout/Tagout)",
        "authority": "OSHA",
        "applies_to_sector": "all",
        "criteria": {"employees_gte": 1, "requires_lockout_program": True},
        "required_actions": [
            "Implement documented lockout/tagout procedures",
            "Provide annual inspection of energy control procedures",
            "Train authorized and affected employees",
        ],
        "source_name": "OSHA 29 CFR 1910.147",
        "source_url": "https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.147",
        "version": "2024",
        "status": "approved",
        "last_verified_on": datetime(2026, 4, 17),
        "expert_reviewer": "Dana Cole, CSP",
        "expert_credentials": "Certified Safety Professional",
        "expert_review_notes": "Reviewed with LOTO section requirements.",
    },
    {
        "code": "OSHA-29CFR-1904",
        "title": "Recording and Reporting Occupational Injuries and Illnesses",
        "authority": "OSHA",
        "applies_to_sector": "all",
        "criteria": {"employees_gte": 11},
        "required_actions": [
            "Maintain OSHA 300, 300A, and 301 forms",
            "Post annual 300A summary",
            "Report severe injuries/fatalities within OSHA timelines",
        ],
        "source_name": "OSHA Recordkeeping 29 CFR Part 1904",
        "source_url": "https://www.osha.gov/recordkeeping/recording",
        "version": "2026",
        "status": "approved",
        "last_verified_on": datetime(2026, 4, 17),
        "expert_reviewer": "Mina Patel, CIH",
        "expert_credentials": "Certified Industrial Hygienist",
        "expert_review_notes": "Verified recording thresholds and form requirements.",
    },
    {
        "code": "EPA-40CFR-262",
        "title": "Hazardous Waste Generator Standards",
        "authority": "EPA",
        "applies_to_sector": "all",
        "criteria": {"annual_hazardous_waste_kg_gt": 100},
        "required_actions": [
            "Determine hazardous waste generator category",
            "Use manifest and labeling requirements where applicable",
            "Maintain accumulation and shipping records",
        ],
        "source_name": "EPA Hazardous Waste Generator Requirements",
        "source_url": "https://www.epa.gov/hwgenerators/hazardous-waste-generator-regulatory-summary",
        "version": "2025",
        "status": "approved",
        "last_verified_on": datetime(2026, 4, 17),
        "expert_reviewer": "Alex Tran, CHMM",
        "expert_credentials": "Certified Hazardous Materials Manager",
        "expert_review_notes": "Verified against EPA regulatory summary and Part 262 references.",
    },
    {
        "code": "EPA-EPCRA-312",
        "title": "EPCRA Tier II Hazardous Chemical Inventory Reporting",
        "authority": "EPA",
        "applies_to_sector": "all",
        "criteria": {"stores_hazardous_chemicals": True},
        "required_actions": [
            "Evaluate if on-site chemical thresholds trigger Tier II reporting",
            "Submit annual Tier II report to SERC/LEPC/fire department as required",
            "Retain submission and inventory records",
        ],
        "source_name": "EPA Tier II Forms and Instructions",
        "source_url": "https://www.epa.gov/epcra/tier-ii-forms-and-instructions",
        "version": "2025",
        "status": "approved",
        "last_verified_on": datetime(2026, 4, 17),
        "expert_reviewer": "Alex Tran, CHMM",
        "expert_credentials": "Certified Hazardous Materials Manager",
        "expert_review_notes": "Confirmed annual Tier II submission requirements.",
    },
    {
        "code": "FDA-21CFR-117",
        "title": "Current Good Manufacturing Practice, Hazard Analysis, and Risk-Based Preventive Controls for Human Food",
        "authority": "FDA",
        "applies_to_sector": "food",
        "criteria": {"produces_human_food": True},
        "required_actions": [
            "Implement cGMP and preventive controls plan",
            "Conduct hazard analysis and maintain records",
            "Verify supplier controls and corrective actions",
        ],
        "source_name": "FDA cGMP and Preventive Controls",
        "source_url": "https://www.fda.gov/food/guidance-regulation-food-and-dietary-supplements/current-good-manufacturing-practices-cgmps-food-and-dietary-supplements",
        "version": "2025",
        "status": "approved",
        "last_verified_on": datetime(2026, 4, 17),
        "expert_reviewer": "Jules Romero, PCQI",
        "expert_credentials": "Preventive Controls Qualified Individual",
        "expert_review_notes": "Mapped controls to FDA Part 117 framework.",
    },
]
